# Generated by Django 5.2.1 on 2025-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttermreview',
            name='recommend_for_advancement',
            field=models.BooleanField(default=True, help_text="Teacher's recommendation for student advancement to next standard"),
        ),
    ]
