# Generated by Django 5.2 on 2025-05-13 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_year_start_year'),
        ('reports', '0001_initial'),
        ('schools', '0004_administrationstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('test_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Mid-Term Test'), ('endterm', 'End of Term Test'), ('project', 'Project'), ('other', 'Other')], max_length=20)),
                ('test_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to='schools.teacher')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='schools.standard')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='academics.year')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_inclusions', to='academics.standardsubject')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reports.test')),
            ],
            options={
                'unique_together': {('test', 'standard_subject')},
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='schools.student')),
                ('test_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='reports.testsubject')),
            ],
            options={
                'unique_together': {('test_subject', 'student')},
            },
        ),
    ]
