# Generated by Django 5.2.1 on 2025-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubject',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Whether this subject is active for this test'),
        ),
        migrations.AlterField(
            model_name='testsubject',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
