# Generated by Django 5.2.1 on 2025-06-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_standardteacher_teacher'),
        ('core', '0001_initial'),
        ('reports', '0002_testsubject_enabled_alter_testsubject_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When this test was finalized', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='Who finalized this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_tests', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Whether this test has been finalized'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Mid-Term Test'), ('project', 'Project'), ('final_exam', 'Final Exam'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_assessment_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Average percentage of all term assessments', max_digits=5)),
                ('final_exam_score', models.PositiveIntegerField(default=0, help_text='Raw score on final exam')),
                ('final_exam_max_score', models.PositiveIntegerField(default=100, help_text='Maximum possible score on final exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='academics.standardsubject')),
                ('term_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='reports.studenttermreview')),
            ],
            options={
                'verbose_name': 'Student Subject Score',
                'verbose_name_plural': 'Student Subject Scores',
                'unique_together': {('term_review', 'standard_subject')},
            },
        ),
    ]
