# Generated by Django 5.2 on 2025-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0002_studenttermreview_recommend_for_advancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttermreview',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When this report was finalized', null=True),
        ),
        migrations.AddField(
            model_name='studenttermreview',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who finalized this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_reports', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='studenttermreview',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Whether this report has been finalized by the teacher'),
        ),
        migrations.AddField(
            model_name='studenttermreview',
            name='pdf_generated',
            field=models.BooleanField(default=False, help_text='Whether PDF has been generated for this report'),
        ),
        migrations.AddField(
            model_name='studenttermreview',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was generated', null=True),
        ),
        migrations.AddField(
            model_name='studenttermreview',
            name='pdf_path',
            field=models.CharField(blank=True, help_text='Path to the generated PDF file', max_length=500),
        ),
    ]
