# Generated by Django 5.2 on 2025-05-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_year_start_year'),
        ('reports', '0002_test_testsubject_testscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='status',
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_this_year', to='academics.year'),
        ),
    ]
