# Generated by Django 5.2 on 2025-11-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_studenttermreview_finalized_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttermreview',
            options={'ordering': ['student__last_name', 'student__first_name']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['test_date']},
        ),
        migrations.AlterModelOptions(
            name='testscore',
            options={'ordering': ['student__last_name', 'student__first_name'], 'verbose_name': 'Test Score', 'verbose_name_plural': 'Test Scores'},
        ),
    ]
