version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - school_network

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - school_network

  nginx:
    image: nginx:1.25
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - school_network

networks:
  school_network:

volumes:
  postgres_data:
  static_volume:
