# Generated by Django 5.2 on 2025-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('administration', 'Administration')], max_length=20),
        ),
    ]
