# Generated by Django 5.2 on 2025-05-03 14:30

from django.db import migrations


def update_staff_to_administration(apps, schema_editor):
    """
    Update existing 'staff' user_type values to 'administration'
    """
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(user_type='staff').update(user_type='administration')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_staff_to_administration'),
    ]

    operations = [
        migrations.RunPython(update_staff_to_administration),
    ]
