# Generated by Django 5.2 on 2025-04-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('term1_start_date', models.DateField()),
                ('term1_end_date', models.DateField()),
                ('term1_school_days', models.PositiveIntegerField()),
                ('term2_start_date', models.DateField()),
                ('term2_end_date', models.DateField()),
                ('term2_school_days', models.PositiveIntegerField()),
                ('term3_start_date', models.DateField()),
                ('term3_end_date', models.DateField()),
                ('term3_school_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='StandardTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_assignments', to='schools.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_teachers', to='academics.year')),
            ],
            options={
                'unique_together': {('year', 'standard', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StandardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='schools.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_assignments', to='academics.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_subjects', to='academics.year')),
            ],
            options={
                'unique_together': {('year', 'standard', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_enrollments', to='schools.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.year')),
            ],
            options={
                'unique_together': {('year', 'standard', 'student')},
            },
        ),
    ]
