# Generated by Django 5.2.1 on 2025-09-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('schools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='schools.school')),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('school', 'start_year')},
            },
        ),
        migrations.CreateModel(
            name='StandardEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='schools.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_enrollments', to='schools.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_standard_enrollments', to='academics.schoolyear')),
            ],
            options={
                'verbose_name': 'Standard Enrollment',
                'verbose_name_plural': 'Standard Enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.standard')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_assignments', to='core.userprofile')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_teachers', to='academics.schoolyear')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(blank=True, help_text='Date when student was enrolled in the school', null=True)),
                ('graduation_date', models.DateField(blank=True, help_text='Date when student graduated or left', null=True)),
                ('transfer_notes', models.TextField(blank=True, help_text='Notes about student transfers or status changes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if student has graduated or left the school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_registrations', to='schools.student')),
            ],
            options={
                'verbose_name': 'School Enrollment',
                'verbose_name_plural': 'School Enrollments',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('school', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Position or role in the school (e.g., Principal, Vice Principal, Secretary)', max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, help_text='Date when staff member was hired', null=True)),
                ('transfer_notes', models.TextField(blank=True, help_text='Notes about staff transfers or role changes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if staff member has left the school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_employment', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'School Staff Member',
                'verbose_name_plural': 'School Staff Members',
                'ordering': ['staff__user__last_name', 'staff__user__first_name'],
                'unique_together': {('school', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='StandardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_subjects', to='core.userprofile')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='schools.standard')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_subjects', to='academics.schoolyear')),
            ],
            options={
                'unique_together': {('year', 'standard', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.schoolyear')),
            ],
            options={
                'ordering': ['year', 'term_number'],
                'unique_together': {('year', 'term_number')},
            },
        ),
    ]
