# Generated by Django 5.2 on 2025-05-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('schools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='schools.school')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Position or role in the school', max_length=100, null=True)),
                ('transfer_notes', models.TextField(blank=True, help_text='Notes about staff transfers', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='core.userprofile')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_staff', to='academics.schoolyear')),
            ],
            options={
                'ordering': ['-year__start_year', 'staff__user__last_name', 'staff__user__first_name'],
                'unique_together': {('year', 'school', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_enrollments', to='schools.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.schoolyear')),
            ],
            options={
                'unique_together': {('year', 'standard', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StandardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_subjects', to='core.userprofile')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='schools.standard')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_subjects', to='academics.schoolyear')),
            ],
            options={
                'unique_together': {('year', 'standard', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='StandardTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.standard')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='standard_assignments', to='core.userprofile')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_teachers', to='academics.schoolyear')),
            ],
            options={
                'unique_together': {('year', 'standard', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.schoolyear')),
            ],
            options={
                'ordering': ['year', 'term_number'],
                'unique_together': {('year', 'term_number')},
            },
        ),
    ]
