# Generated by Django 5.2.1 on 2025-09-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_year_verified', models.BooleanField(default=False, help_text='Next academic year setup verified')),
                ('teachers_unassigned', models.BooleanField(default=False, help_text='All teachers unassigned from classes')),
                ('teachers_unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('std5_processed', models.BooleanField(default=False, help_text='Standard 5 students graduated')),
                ('std5_processed_at', models.DateTimeField(blank=True, null=True)),
                ('std4_processed', models.BooleanField(default=False, help_text='Standard 4 students advanced')),
                ('std4_processed_at', models.DateTimeField(blank=True, null=True)),
                ('std3_processed', models.BooleanField(default=False, help_text='Standard 3 students advanced')),
                ('std3_processed_at', models.DateTimeField(blank=True, null=True)),
                ('std2_processed', models.BooleanField(default=False, help_text='Standard 2 students advanced')),
                ('std2_processed_at', models.DateTimeField(blank=True, null=True)),
                ('std1_processed', models.BooleanField(default=False, help_text='Standard 1 students advanced')),
                ('std1_processed_at', models.DateTimeField(blank=True, null=True)),
                ('inf2_processed', models.BooleanField(default=False, help_text='Infant 2 students advanced')),
                ('inf2_processed_at', models.DateTimeField(blank=True, null=True)),
                ('inf1_processed', models.BooleanField(default=False, help_text='Infant 1 students advanced')),
                ('inf1_processed_at', models.DateTimeField(blank=True, null=True)),
                ('new_students_registered', models.BooleanField(default=False, help_text='New Infant 1 students registered')),
                ('new_students_registered_at', models.DateTimeField(blank=True, null=True)),
                ('teachers_reassigned', models.BooleanField(default=False, help_text='Teachers assigned to new classes')),
                ('teachers_reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('from_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='academics.schoolyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_transitions', to='schools.school')),
                ('to_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='academics.schoolyear')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('school', 'from_year', 'to_year')},
            },
        ),
    ]
