# Generated by Django 5.2 on 2025-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='start_year',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
