# Generated by Django 5.2 on 2025-11-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_add_transition_model'),
        ('core', '0002_add_term_finalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When this term was finalized', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='Who finalized this term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_terms', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='term',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Whether this term has been finalized (no more tests can be created)'),
        ),
    ]
