# Generated by Django 5.2.1 on 2025-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_schoolstaff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='standardsubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
