# Generated by Django 5.2 on 2025-11-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_term_finalization'),
        ('core', '0002_add_term_finalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolenrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, help_text='User who enrolled this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_enrollments_made', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_additions_made', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='standardenrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, help_text='User who enrolled this student in the class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_enrollments_made', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='standardteacher',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments_made', to='core.userprofile'),
        ),
    ]
