# Generated by Django 5.2.1 on 2025-06-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_enrollment_is_active_standardsubject_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='standardsubject',
            name='is_active',
        ),
    ]
