# Generated by Django 5.2.1 on 2025-06-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_enrollment_is_active_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='standardteacher',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='standardteacher',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.standard'),
        ),
        migrations.AlterField(
            model_name='standardteacher',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.standard'),
        ),
    ]
