# Generated by Django 5.2.1 on 2025-06-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_update_assignment_history'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_assignments', to='core.userprofile'),
        ),
    ]
