# Generated by Django 5.2.1 on 2025-08-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_standardteacher_teacher'),
        ('core', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolstaff',
            options={'ordering': ['staff__user__last_name', 'staff__user__first_name'], 'verbose_name': 'School Staff Member', 'verbose_name_plural': 'School Staff Members'},
        ),
        migrations.AlterUniqueTogether(
            name='schoolstaff',
            unique_together={('school', 'staff')},
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date when staff member was hired', null=True),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False if staff member has left the school'),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='position',
            field=models.CharField(blank=True, help_text='Position or role in the school (e.g., Principal, Vice Principal, Secretary)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_employment', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='transfer_notes',
            field=models.TextField(blank=True, help_text='Notes about staff transfers or role changes', null=True),
        ),
        migrations.RemoveField(
            model_name='schoolstaff',
            name='year',
        ),
    ]
