# Generated by Django 5.2.1 on 2025-08-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_year_from_school_staff'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(blank=True, help_text='Date when student was enrolled in the school', null=True)),
                ('graduation_date', models.DateField(blank=True, help_text='Date when student graduated or left', null=True)),
                ('transfer_notes', models.TextField(blank=True, help_text='Notes about student transfers or status changes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if student has graduated or left the school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_registrations', to='schools.student')),
            ],
            options={
                'verbose_name': 'School Enrollment',
                'verbose_name_plural': 'School Enrollments',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('school', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StandardEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='schools.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='schools.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_enrollments', to='academics.schoolyear')),
            ],
            options={
                'verbose_name': 'Standard Enrollment',
                'verbose_name_plural': 'Standard Enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
