# Generated by Django 5.2.1 on 2025-08-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_create_school_enrollment_and_standard_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardenrollment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_standard_enrollments', to='academics.schoolyear'),
        ),
    ]
