# Generated by Django 5.2.1 on 2025-09-21 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_update_standardenrollment_related_name'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_enrollments', to='schools.student'),
        ),
    ]
