# Generated by Django 5.2 on 2025-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
