# Generated by Django 5.2 on 2025-04-27 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principal',
            new_name='principal_name',
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_notes',
            field=models.TextField(blank=True, help_text='Notes about student transfers', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='transfer_notes',
            field=models.TextField(blank=True, help_text='Notes about teacher transfers', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_email',
            field=models.EmailField(default='teacher@me.com', max_length=254),
            preserve_default=False,
        ),
    ]
