# Generated by Django 5.2 on 2025-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_principal_school_principal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='cumana-rc', help_text='URL-friendly version of the school name', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
