# Generated by Django 5.2 on 2025-11-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_add_groups_support'),
        ('schools', '0002_alter_school_logo'),
    ]

    operations = [
    ]
