# Generated by Django 5.2 on 2025-11-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_term_finalization'),
        ('schools', '0003_merge_0002_add_groups_support_0002_alter_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this student record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to='core.userprofile'),
        ),
    ]
